name: merloc
description: "Dart Package for merge localization based on folder"
version: 0.0.4
homepage: https://github.com/aglis-lab

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0

executables:
  merloc: merloc
